repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-added-large-files
        args: [--maxkb=100]
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: [--fix=lf]
        files: '\.sh$|^Dockerfile$|^Makefile$'
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-toml
        args: ['--unsafe']

# Conflicts with autopep8:
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.11.5
#     hooks:
#     -   id: isort

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=120]

# Broken hook:
# -   repo: https://github.com/htacg/tidy-html5
#     rev: master
#     hooks:
#     -   id: tidy

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
