install_poetry:
	curl -sSL https://install.python-poetry.org | python3 -
	poetry --version

install:
	poetry install

test:
	poetry run pre-commit run --all
	poetry run pytest --cov src/ -v -m "not integration_test" tests/

docker-build:
	DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile -t $$IMAGE_NAME .
	mkdir -p artifacts/docker_images
	docker image save --output artifacts/docker_images/$$IMAGE_NAME.tar $$IMAGE_NAME

docker-integration-test:
	echo "AWS_ACCESS_KEY_ID: $$AWS_ACCESS_KEY_ID"
	docker run -e "ENV=$$ENV" --workdir=/src $$IMAGE_NAME sh -c "pytest -v -m 'integration_test' tests"

docker-push:
	if [ -n  "$(VERSION_TAG)" ]; then \
		docker image tag $$IMAGE_NAME $$ECR_REGISTRY/$$ECR_REPOSITORY:$(VERSION_TAG); \
	fi
	docker image tag $$IMAGE_NAME $$ECR_REGISTRY/$$ECR_REPOSITORY:latest
	docker image tag $$IMAGE_NAME $$ECR_REGISTRY/$$ECR_REPOSITORY:$$IMAGE_TAG
	docker image push --all-tags $$ECR_REGISTRY/$$ECR_REPOSITORY
