name: Build Python Library using Poetry
description: "Build and test our Python package"

on:
  push:
    branches:
      - main # Change this to the name of your main branch


runs:
  using: composite
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      shell: bash
      run: make install_poetry

    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'poetry' # caching poetry dependencies

    - name: Install project
      shell: bash
      run: make install

    - name: Create artifacts directory
      shell: bash
      run: mkdir -p artifacts

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@master
    #   with:
    #     role-to-assume: ${{ env.AWS_ROLE }}
    #     aws-region: eu-central-1

    - name: Run test
      shell: bash
      run: make test

    # - name: Build Docker image
    #   shell: bash
    #   run: make docker-build

    # - name: Temporarily save Docker image
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: docker-artifact
    #     path: artifacts/docker_images
    #     retention-days: 1
