name: pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.4.2
        # virtualenvs-create: true
        # virtualenvs-in-project: true

    - name: Install Dependencies
      run: poetry install

    - name: Verify GPU availability
      #run: poetry shell
      run: python -c "import torch; assert torch.cuda.is_available()"

    # - name: Run Tests
    #   run: poetry run pytest
