name: Python Test

on:
  push:
    branches:
      - main # Change this to the name of your main branch

jobs:
  pre-commit_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Pip install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      # This should be part of test, not pre-commit:
      # - name: Pip install all requirements
      #   run: pip install -r requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files


# Tests have been included in the precommit, and are therefore no longer necessary to include separately
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.10"]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Run tests
  #     run: python -m pytest
